var tipos = {
    "ghost": "fantasma",
    "electric": "elétrico",
    "ice": "gelo",
    "water": "água",
    "grass": "grama",
    "ground": "solo",
    "bug": "inseto",
    "rock": "pedra",
    "fire": "fogo",
    "flying": "voador",
    "poison": "venenoso",
    "fighting": "lutador",
    "steel": "aço",
    "psychic": "psíquico",
    "dragon": "dragão",
    "dark": "sombrio",
    "fairy": "fada",
    "shadow": "fogo",
    "undefined": "indefinido",
    "normal": "normal"
}